# Generated by Django 3.1.2 on 2020-10-17 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
        ('console_app', '0001_initial'),
        ('user_faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamefaquser',
            name='favorited_games',
            field=models.ManyToManyField(related_name='user_fav', to='game_app.Game'),
        ),
        migrations.AddField(
            model_name='gamefaquser',
            name='followers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='gamefaquser',
            name='preferred_systems',
        ),
        migrations.AddField(
            model_name='gamefaquser',
            name='preferred_systems',
            field=models.ManyToManyField(blank=True, to='console_app.Console'),
        ),
        migrations.CreateModel(
            name='User_Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('post_date', models.DateField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('touser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggeduser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
