# Generated by Django 3.1.2 on 2020-10-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamefaquser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
