# Generated by Django 3.1.2 on 2020-10-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_faq', '0003_gamefaquser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamefaquser',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
