# Generated by Django 3.1.2 on 2020-10-15 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_app', '0001_initial'),
        ('console_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameFaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('difficulty', models.CharField(choices=[('EASY', 'EASY'), ('INTERMEDIATE', 'INTERMEDIATE'), ('HARD', 'HARD')], max_length=85)),
                ('ptype', models.CharField(choices=[('CHEATCODES', 'CHEATCODES'), ('GAMEFAQ', 'GAMEFAQ')], default='GAMEFAQ', max_length=25)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamefaq_author', to=settings.AUTH_USER_MODEL)),
                ('consoles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='console_gamefaq', to='console_app.console')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_game', to='game_app.game')),
            ],
        ),
    ]
