# Generated by Django 3.1.2 on 2020-10-13 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('console_app', '0001_initial'),
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameFaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('difficulty', models.CharField(choices=[('EASY', 'EASY'), ('INTERMEDIATE', 'INTERMEDIATE'), ('HARD', 'HARD')], max_length=85)),
                ('postdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamefaq_author', to=settings.AUTH_USER_MODEL)),
                ('consoles', models.ManyToManyField(blank=True, related_name='console_gamefaq', to='console_app.Console')),
                ('game', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_game', to='game_app.game')),
            ],
        ),
    ]
