# Generated by Django 3.1.2 on 2020-10-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefaq_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamefaq',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamefaq',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
