# Generated by Django 3.1.2 on 2020-10-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefaq_app', '0002_auto_20201013_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamefaq',
            name='postdate',
        ),
        migrations.AddField(
            model_name='gamefaq',
            name='ptype',
            field=models.CharField(choices=[('CHEATCODES', 'CHEATCODES'), ('GAMEFAQ', 'GAMEFAQ')], default='GAMEFAQ', max_length=25),
        ),
    ]
