# Generated by Django 3.1.2 on 2020-10-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamefaq_app', '0002_gamefaq_faq_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamefaq',
            old_name='faq_game',
            new_name='game',
        ),
    ]
