# Generated by Django 3.1.2 on 2020-10-10 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamefaq_app', '0003_auto_20201009_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamefaq',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamefaq_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
